### ISSUE TITLE
Thiết kế phần insert minh chứng theo dạng mở pop-up và check

### ISSUE THREAD

**Issue by DucDA177** [DucDA177/NP_KDCL#11]

**Comment by NamPhongSoft** [comment]
![image](https://user-images.githubusercontent.com/108246861/175851918-21fdba35-c550-4478-b3c6-8164b58c2fcb.png)
Vào chức năng đổi mật khẩu nhưng không muốn đổi nữa thì cần thêm nút hủy để thoát về màn hình chính

**Comment by NamPhongSoft** [comment]
Trong trường hợp vừa muốn cho người ngày thu thập minh chứng và cho viết báo cáo thì phải làm sao? Hiện tại thấy chỉ tích chọn được 1 lựa chọn.
![image](https://user-images.githubusercontent.com/108246861/175852221-f4d9823b-4b5f-4fd6-b356-965064021e2f.png)

**Comment by DucDA177** [comment]
> Trong trường hợp vừa muốn cho người ngày thu thập minh chứng và cho viết báo cáo thì phải làm sao? Hiện tại thấy chỉ tích chọn được 1 lựa chọn. ![image](https://user-images.githubusercontent.com/108246861/175852221-f4d9823b-4b5f-4fd6-b356-965064021e2f.png)

phần này a nhấn giữ phím CTRL và tích chọn thì nó sẽ chọn nhiều
