### ISSUE TITLE
Không đọc được minh chứng trong báo cáo đánh giá cấp phòng

### ISSUE THREAD

**Issue by tuananhnamphong** [DucDA177/NP_KDCL#24]
![image](https://user-images.githubusercontent.com/112921039/194235405-e677b9eb-e9f1-4ae9-924d-1978fdcea5e7.png)

**Comment by tuananhnamphong** [comment]
Ở báo cáo cấp trường thì đã được phần này? 
TRong trường hợp đưa minh chứng đúng định dạng có tự động liên kết được không? vì nhiều cái copy ra word rồi lại copy bị lại phần mềm? Ví dụ: ĐỊnh dạng [H1-1.4-11] là tự động đọc được.

**Comment by tuananhnamphong** [comment]
Khi quét mã báo cáo.
![image](https://user-images.githubusercontent.com/112921039/194236500-693ba82b-ceab-457c-a9f9-bdc2a6801201.png)
Người dùng có thể đọc được báo cáo bất cứ lúc nào. Nhưng trong quá trình đọc báo cáo, click vào minh chứng thì bắt đăng nhập mới đọc được.
![image](https://user-images.githubusercontent.com/112921039/194236873-d4b30c82-57e7-4a4f-8805-9cf3ac213e4a.png)

**Comment by DucDA177** [comment]
> Ở báo cáo cấp trường thì đã được phần này? TRong trường hợp đưa minh chứng đúng định dạng có tự động liên kết được không? vì nhiều cái copy ra word rồi lại copy bị lại phần mềm? Ví dụ: ĐỊnh dạng [H1-1.4-11] là tự động đọc được.

Phần này phải làm ở phần mềm mình mới đc cơ anh ạ, còn làm từ word rồi copy lại ko đc đâu.

**Comment by tuananhnamphong** [comment]
Ok em
