### ISSUE TITLE
Không hiển thị Đoàn đánh giá trong Báo cáo đánh giá ngoài

### ISSUE THREAD

**Issue by DucDA177** [DucDA177/NP_KDCL#47]
Thông tin đánh giá ngoài => Báo cáo đánh giá ngoài
Lúc in báo cáo không hiển thị thông tin thành viên đoàn
![image](https://user-images.githubusercontent.com/48557721/207065562-7b62e045-51c1-407c-b339-f95620c0448b.png)

**Comment by ducvu1998** [comment]
fixed
